import type { Metadata } from "next";

import { Inter } from "next/font/google";

import {
    QueryClient,
    useQueryClient,
    QueryClientProvider,
} from '@tanstack/react-query'

import SSRProvider from 'react-bootstrap/SSRProvider'

import 'bootstrap/dist/css/bootstrap.css';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            retry: false,
            refetchOnWindowFocus: false,
        },
    },
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <QueryClientProvider client={queryClient}>
                    <SSRProvider>
                        {children}
                    </SSRProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
