import { ReactNode } from 'react'

import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { PrimeReactProvider } from 'primereact/api'

import 'primereact/resources/themes/lara-light-blue/theme.css'
import 'primeflex/primeflex.css'

import "./globals.css";

import { ReactQueryProvider } from './providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ReactQueryProvider>
            <PrimeReactProvider>
                {children}
            </PrimeReactProvider>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
